language: ruby
rvm:
  - "2.4.0"
  - "2.3.3"
  - "2.2.6"
  - "2.1.10"
  - "2.0.0"
env: CODECLIMATE_REPO_TOKEN=efdb12c380287a25b2b26362aa710a9b59020122cbe4edecf0d353bf50e0046a
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b740ebfeb7e0dba10293
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
